import React from 'react';
import type { Metadata } from "next";
import "./globals.css";
import Layouts from "@/layouts";
import Xiaomi from '@/components/xiaomi';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
